<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@	page import="java.util.ArrayList"%>
<%@ page import="rendezvous.Login"%>
<%@ page import="rendezvous.Customer"%>
<%@ page import="rendezvous.UserProfile"%>
<%@ page import="rendezvous.SuggestDate"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="Stylesheet/topbar.css" type="text/css" rel="stylesheet">
<link href="Stylesheet/help.css" type="text/css" rel="stylesheet">
</head>
<title>Help</title>
<body>
	<%
	try {
		if (!session.getAttribute("staffSession").equals("MA")) {
			response.sendRedirect("staffLogin.jsp");
		}
		if (session.getAttribute("staffSSN") == null) {
			response.sendRedirect("staffLogin.jsp");
		}
	} catch (Exception ex) {
		response.sendRedirect("staffLogin.jsp");
		return;
	}
	%>
	<div class="titleBar"></div>
	<div class=rendezvous>Rendezvous</div>
	<!--=============================================================================-->
	<!--=============================================================================-->
	<!--=============================================================================-->
	<!-- Button -->
	<div class="signOut">
		<a href="managerHome.jsp">Back</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="signOut.jsp">Sign Out</a>
	</div>
	<!--=============================================================================-->
	<!--=============================================================================-->
	<!--=============================================================================-->
	<div class="helpTOP_Icon"><i class="fa fa-info-circle"></i></div>
	<div class="helpTOP_Text">Help</div>
	<!--=============================================================================-->
	<!--=============================================================================-->
	<!--=============================================================================-->
	<div class="helpTitle">
		Manager Level
		<div class="helpList">
			Add, Edit and Delete information for an employee
			<div class="helpText">
				Click the "Employee Center" on the homepage of the manager.
			</div>
		</div>
		<div class="helpList">
			Obtain a sales report for a particular month
			<div class="helpText">
				Click the "Sale Report" on the homepage of the manager.
			</div>
		</div>
		<div class="helpList">
			Produce a comprehensive listing of all users
			<div class="helpText">
				Click the "User Portrait" on the homepage of the manager.
			</div>
		</div>
		<div class="helpList">
			Produce a list of dates by calendar date or by customer name
			<div class="helpText">
				Click the "Date List" on the homepage of the manager.
			</div>
		</div>
		<div class="helpList">
			Produce a summary listing of revenue generated by dates on a particular calendar date
			<div class="helpText">
				1. Click the "Date List" on the homepage of the manager.
				<br>
				2. Click "Summary Revenue Calendar"
			</div>
		</div>
		<div class="helpList">
			Produce a summary listing of revenue generated by dates involving a particular customer
			<div class="helpText">
				1. Click the "Date List" on the homepage of the manager.
				<br>
				2. Click "Summary Revenue Customer"
			</div>
		</div>
		<div class="helpList">
			Determine which customer representative generated most total revenue
			<div class="helpText">
				1. Click the "Date List" on the homepage of the manager.
				<br>
				2. Click "Representative Generated Most Total Revenue"
			</div>
		</div>
		<div class="helpList">
			Determine which customer generated most total revenue
			<div class="helpText">
				1. Click the "Date List" on the homepage of the manager.
				<br>
				2. Click "Customer Generated Most Total Revenue"
			</div>
		</div>
		<div class="helpList">
			Produce a list of most active customers
			<div class="helpText">
				1. Click the "Customer Analysis" on the homepage of the manager.
				<br>
				2. Click "Most Active Customer"
			</div>
		</div>
		<div class="helpList">
			Produce a list of all customers who have dated a particular customer
			<div class="helpText">
				1. Click the "Customer Analysis" on the homepage of the manager.
				<br>
				2. Click "All Customers Who Have Dated A Particular Customer"
			</div>
		</div>
		<div class="helpList">
			Produce a list of the highest-rated customers
			<div class="helpText">
				1. Click the "Customer Analysis" on the homepage of the manager.
				<br>
				2. Click "Highest_Rated Customer"
			</div>
		</div>
		<div class="helpList">
			Produce a list of the highest-rated calendar dates to have a date on
			<div class="helpText">
				1. Click the "Customer Analysis" on the homepage of the manager.
				<br>
				2. Click "Highest-rated Calendar Dates to Have A Date On"
			</div>
		</div>
		<div class="helpList">
			Backing up the database files
			<br>
			<img src="Stylesheet/Image/backup.png" height="600" width="550">
		</div>
	</div>
</body>
</html>

